config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resource :comments do
    get ':id', to: 'comments#show'
    get ':id/like', to: 'comments#like', as: 'like'          # GET ?! Toutes les routes qui écrivent dans la base 
    get ':id/dislike', to: 'comments#dislike', as: 'dislike' # DOIVENT utiliser POST/PUT/DELETE, jamais GET !
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  validates :title, :content, presence: true

  before_save :default_values

  def default_values
    self.likes ||= 0
    self.dislikes ||= 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    if Comment.new(post_params).save
      redirect_to root_path
    end
  end

  def post_params
    params.require(:comment).permit(:title, :content)
        .merge(user_id: current_user.id)
  end

  def like
    @comment = Comment.find(params[:id])
    if @comment
      @comment.increment!(:likes)
      redirect_to root_path
    end
  end

  def dislike
    @comment = Comment.find(params[:id])
    if @comment
      @comment.increment!(:dislikes)
      redirect_to root_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @comments = Comment.all.order('created_at DESC').first(5)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div>

  <p class="logout">
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  </p>

  <h2>Ajouter un commentaire</h2>
  <%= form_tag comments_path, method: :post do %>
    <%= text_field_tag 'comment[title]', '', placeholder: 'Titre' %>
    <%= text_area_tag 'comment[content]', '', placeholder: 'Saisissez votre commentaire' %>
    <%= submit_tag 'Save' %>
  <% end %>

  <h2>Commentaires (<%= @comments.count %>)</h2>
  <ul class="comments">
    <% @comments.each do |comment| %>
      <li class="comment">
        <small>#<%= comment.id %> written <%= comment.created_at %> by <%= comment.user.email %></small>
        <h3><%= comment.title %></h3>
        <p><%= comment.content %></p>
        <p class="actions">
          <%= link_to 'Like', like_comments_path(comment) %> (<b><%= comment.likes %></b>) -
          <%= link_to 'Dislike', dislike_comments_path(comment) %> (<b><%= comment.dislikes %></b>)
        </p>
      </li>
    <% end %>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TpComments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>